### ISSUE TITLE
ExpireCallback calls on Remove() item

### ISSUE THREAD

**Issue by evassilyev** [jellydator/ttlcache#70]
ExpireCallback is a common callback for two cases:
1. Item expired by TTL
2. Item removed.
It's not documented behaviour (but it's easy to check through the code).
I guess, you should add separated callback for Remove() call, or configure cache to do not call ExpireCallback on removing an item, because there's no way to remove the item with TTL without calling the expiration callback if it was set.

**Comment by swithek** [comment]
The v3 has a general `OnEviction` [method](https://github.com/jellydator/ttlcache/blob/master/cache.go#L488) that can be used to register callbacks for all eviction types. However, the `EvictionReason` parameter can be checked if there is a need to handle only one kind of eviction (e.g., one that is caused by expiration).
