### ISSUE TITLE
Returning loader errors

### ISSUE THREAD

**Issue by lafriks** [jellydator/ttlcache#74]
With new version v3 there is currently no way to return loader (either default or getter) error as Get returns only item and there is no way to propagate errors back to caller.

**Comment by Neal** [comment]
I came here to report the same issue as we just migrated to v3 and realized this regression

**Comment by lafriks** [comment]
There is workaround for this but only for local loader and imho it's anti-pattern but you can do:
```go
var err error
item := c.Get("x", ... func(...) {
  err = errors.New("error")
}...)
```

**Comment by swithek** [comment]
The current `Get()` implementation cannot produce any errors and deals only with items that either exist (non-nil return value) or don't (nil return value), so there's no need to have an error return value there (in v2, the `Get()` method used to have an error return value because it performed a few additional checks that aren't needed in v3). The same principle applies to the `Loader` interface: it's allowed to return only nil (when an error occurs or an item isn't found) or non-nil values. There may be cases when you want to perform an error-producing action inside the `Loader` implementation, however, these aren't the cases that should concern the `ttlcache` library (again, because its main purpose is to store and load cache items, not to handle non-library-related errors). 

Nevertheless, sometimes Loader's errors do need to be propagated and handled at the same location where the cache's `Get()` is called, that's partly the reason why `Loader` is an interface and not a simple func type. This means you can have the following reusable implementation:
```go
type LoaderErr[K, V] struct {
    fn func(*Cache[K, V], K) (*Item[K, V], error)
    err error
}

func NewLoaderErr[K comparable, V any](fn func(*Cache[K, V], K) (*Item[K, V], error)) *LoaderErr {
    return &LoaderErr{fn: fn}
}

func (l *LoaderErr[K, V]) Load(c *Cache[K, V], key K) *Item[K, V] {
    item, err := l.fn(c, key)
    if err != nil {
          l.err = err
          return nil
    }
    return item
}

func (l *LoaderErr[K, V]) Err() error {
     return l.err
}
```

And use it like this:
```go
loader := NewLoaderErr[K, V](func(){...})
item := cache.Get("key", ttlcache.WithLoader[K, V](loader))
if err := loader.Err(); err != nil {
     // ...
}
```

This approach is similar to the one employed by the sql.Rows type's [Err() and Next() methods](https://pkg.go.dev/database/sql#Rows.Err).

**Comment by lafriks** [comment]
This pretty much the same as my workaround but problem is that you can not use global loader for this.

For example you want to cache data coming from database or as in readme from file.

```go
loader := ttlcache.LoaderFunc[string, string](
	func(c *ttlcache.Cache[string, string], key string) *ttlcache.Item[string, string] {
		// load from file/make an HTTP request
		// !!! How do you handle file reading exception or HTTP request failure or database request error???
		item := c.Set("key from file", "value from file")
		return item
	},
)

cache := ttlcache.New[string, string](
	ttlcache.WithLoader[string, string](loader),
)

item := cache.Get("key from file")
```

This makes loader pretty much useless as you can not just wrap it around some data source you want to cache.

**Comment by swithek** [comment]
Without using an additional map-like structure for errors, you wouldn't be able to use this implementation as a global loader, that's true. But what's stopping you from using it as a `Get()` option? It's the same thing, only the location is different.

Alternatively, you could use the following type as the value of all items:
```go
type Value[T any] struct {
     Val T
     Err err
}
```
Then, just set the error field inside the Loader's implementation and return the whole item (it's propagated to the caller and the cache isn't updated). Although this approach looks much more like a dirty workaround than having an implementation with an Err() method.

**Comment by lafriks** [comment]
> Without using an additional map-like structure for errors, you wouldn't be able to use this implementation as a global loader, that's true. But what's stopping you from using it as a `Get()` option? It's the same thing, only the location is different.

Yes but if you need to use same cache in multiple places now you need to duplicate same caller function in many places just because error variable needs to be local.

> Then, just set the error field inside the Loader's implementation and return the whole item (it's propagated to the caller and the cache isn't updated). Although this approach looks much more like a dirty workaround than having an implementation with an Err() method.

But this way such value (that is actually error) will be stored in cache that is not at all what anyone would want. Not talking that it's anti-pattern in go.

**Comment by swithek** [comment]
> Yes but if you need to use same cache in multiple places now you need to duplicate same caller function in many places just because error variable needs to be local.

It would be interesting to see your specific use case, but in a properly designed system I don't see where all this duplication could come from. Instead of passing the implementation as a global loader you would have to pass it as a `Get()` option and that's about it? It's up to you to choose the scope of your loader and since errors need to be local, the `Get()` options is the best place for that.

**Comment by lafriks** [comment]
I use cache for multiple things, mostly app settings that are stored in database that will be used all over the code, depending on app it might be also user sessions and other things that makes sense to be cached. Of course I could make wrappers around this library for all these things just to handle database errors...

**Comment by jspri** [comment]
Everyone else here has covered well the technical approaches and workarounds but I think it might be handy to disambiguate what this package is about:

1. An elegant/simple cache with ttl
2. A tool for making scaling easy that is fairly idiomatic and doesn't have many footguns.

It seems like the advocates to restore errors have been using it more as (2). For me error propagation outwards and context propagation inwards are table stakes for using loaders properly in (2).

If the vision of the package is to be closer to (1), which is an admirable goal, then it might be worth advocates of (2) having a fork.

--------------------
As an aside, it seems like no longer supporting errors from loaders has lead to a change in behaviour. I think in v2 an error from a loader would cause the value not to be cached and for the next request to also hit the loader. In v3 as errors and values are now treated the same it seems like the origin would not be hit again until the `ttl` expires or unless it is done manually (not 100% sure on this). This is probably less likely to flood your origin but could lead to lower reliability as transient errors are more sticky.

**Comment by swithek** [comment]
@jspri, that's a good summary. 

Regarding the usage of `Loader` and its results: in v3, a non-nil loader is treated as a secondary data store and used only when the requested data isn't found the primary/cache store. The results of the loader are merely passed through, they aren't cached or modified in any way (as seen [here](https://github.com/jellydator/ttlcache/blob/master/cache.go#L270)); since the `Loader` implementation has access to the active cache's instance, it's up to it to decide whether to save the data to the primary/cache data store, thus preventing future calls of the loader's `Load()` method with the same key (at least until the associated item expires), or not. In v2, loaders function in a different way: they aren't given direct access to the active cache's instance and their results are cached automatically (as seen [here](https://github.com/jellydator/ttlcache/blob/v2/cache.go#L406)).

The goal of this package is indeed to provide a simple API, however, that doesn't mean that the need for scalability has been sacrificed or completely forgotten, it just has to be achieved by taking a different route than before, in v2. Contrary to how the majority of methods are implemented in v2, the v3 methods don't produce any errors, rather, they can return an item of a second, special state to indicate that a key can't be found. And these two states cover all the needs of the package. The secondary store, or the loader, is only an extension of the primary/cache store, so it wouldn't be right if the part that is optional and dynamic (there may be many different implementations of `Loader`, some of them could be as simple as a map) influenced the design of the core part.

The design of v3 simplifies the usage of all the exported methods and forces the concept of loader to be perceived differently. As I mentioned before, the nil return value indicates the absence of an item, however, it may also be used whenever a loader encounters an error while making an HTTP request or executing a SQL query. Either way, the caller of the `Get()` method should concern themselves only with the presence/absence of an item and not _why_ it's absent (or rather, why it couldn't be retrieved).

There may be cases in which the context of an error that caused an item to be absent is needed, however, these cases are out of scope of this library, at least in v3. If `ttlcache` had to handle/pass around the loader's errors, it would mean that `ttlcache` is partly responsible for the loader's functionality, when in fact it isn't. An instance of cache and a loader should be separate. The loader should only adapt to the data retrieval interface `ttlcache` provides and allow its errors and other states to be handled elsewhere.

**Comment by lafriks** [comment]
To be honest in such case I don't see much point of having loaders at all in this library.

Normally in HTTP request handler I would do:

```go
session, err := sessionCache.Get(sessionId)
if err != nil {
   // respond with internal server error
  return
}

// normal workflow
```

Anyway, I have forked this library for my use case https://github.com/lafriks/ttlcache/ so I'm closing issue here
