### ISSUE TITLE
Get, Set, and Loader should include context.Context in function signature

### ISSUE THREAD

**Issue by wit221** [jellydator/ttlcache#83]
And pass it around correctly.

**Comment by wit221** [comment]
Loader should also accept an error in the return statement and handle it appropriately (potentially with exponential backoff retries, as a config).

Also, weird that the Loader needs to set the item in the cache. It feels like that should be handled by the framework when calling `Get` and getting a cache miss.

**Comment by xmxue** [comment]
+1

**Comment by swithek** [comment]
`context.Context` has been deliberately excluded from the signatures of Get, Set, Delete, etc., because none of these methods benefit from having that, i.e., there are no blocking operations in them that could be cancelled by a context.

The only time when a `context.Context` parameter _might_ be useful is when passing it to a loader. However, `Loader` isn't a guaranteed dependency, it might not be provided at all, or it might have very simple requirements that don't include having a `context.Context` (e.g., maybe data is being loaded from a map of embedded data), but the signature of a method is guaranteed and permanent, so it doesn't really make sense that a non-guaranteed component influences the shape of a guaranteed one. It should be the other way round.

The same thing applies to errors, as mentioned in this issue: https://github.com/jellydator/ttlcache/issues/74

There is a way for a loader to use a context and still be accepted by the cache: you can create your own custom implementation of `Loader` that has access to the context variable, and then pass it to `Get` by using `WithLoader`. You can find an example [here](https://github.com/jellydator/ttlcache/issues/74#issuecomment-1133012806). I think a type implementing `Loader` like this would be a good addition to `ttlcache` to alleviate the inconveniences you're encountering.

Lastly, the reason why the cache instance is provided as a parameter to `Loader` is because the user of the library might want to control when the cache is updated, even when a secondary store, i.e., a loader is being used. Perhaps someone would want the secondary store always to be used when an item isn't inserted from the outside. Again, if this is a problem, you can create your own implementation of `Loader`.

**Comment by tareksha** [comment]
@swithek this suggestion is limited and can't support more complicated cases, e.g. when the actual loader must be wrapped by a suppressed loader. the loader instance must be shared across all calls to `Get()`.

Also the current API does not support errors which forces us to wrap the actual data with a tuple that contains the error and usually we must invalidate the item immediately after it is returned - again because we wrap the loader with a shared suppressed loader.

It should not be too complicated to add a new getter func
```go
GetWithContext(ctx context.Context, key K) (V, error)
```
and a new loader interface 
```go
type LoaderContext[K comparable, V any] interface {
 Load(ctx context.Context, c *Cache[K, V], key K) (*Item[K, V], error)
}
```
and the existing `Loader` type and `Get()` func can simply delegate to the new, more extended functions logic.

**Comment by swithek** [comment]
> Also the current API does not support errors which forces us to wrap the actual data with a tuple that contains the error and usually we must invalidate the item immediately after it is returned

Yes, if my suggested solution were implemented, the loader would have to be ephemeral.

> It should not be too complicated to add a new getter func

Adding a new func would be rather easy, I agree, but clean design of the API still has to be maintained. The main problem arises from the fact that the loader, in the current implementation of `Get()`, is optional, and the shape of the API shouldn't be formed by things that _might be_ but rather by things that _are_:
> However, Loader isn't a guaranteed dependency, it might not be provided at all, or it might have very simple requirements that don't include having a context.Context (e.g., maybe data is being loaded from a map of embedded data), but the signature of a method is guaranteed and permanent, so it doesn't really make sense that a non-guaranteed component influences the shape of a guaranteed one. It should be the other way round.

Nevertheless, having a dedicated `Get()` func for this might be one of the most viable solutions so far, it would just have to accept a loader as a mandatory parameter:
```go
GetWithContextLoader(ctx context.Context, key K, loader LoaderContext, opts Options)
```

(the name of the func is just a placeholder)

**Comment by rowanseymour** [comment]
> the shape of the API shouldn't be formed by things that might be but rather by things that are:

The API you have right now is beautifully simple, and I understand the desire to keep it that way, but it's a shame we can't make this loader paradigm work because it would make _using this library beautifully simple_. 

Realistically a loader is going to be pulling from a database or filesystem or something that can 1) error and 2) block. I can't think of many scenarios where that wouldn't be the case.

What if there was a different cache type that always takes a loader and thus its `Get` signature takes a context and can return an error? `ttlcache.CacheWithSource`? `Get(context.Context, key K) (V, error)`. Trying to make this work with database loading, I'm probably going to end up writing that anyway on top of `ttlcache.Cache`

**Comment by swithek** [comment]
@rowanseymour Yes, I agree, this particular aspect of the library is still less than ideal. Having a separate type for this could be a solution we've been looking, but I'm a bit hesitant to go ahead with this because of all the duplicate code this might produce. As I mentioned in the previous comment, another solution (this time it's slightly updated) would be to have an alternative `Get()` method:
```go
GetContext(ctx context.Context, key K, opts Options) (Item, error)
```

Also, the loader interface (there could be a separate `LoaderContext` interface) would have a method that returns an error and accepts a context. The options struct would allow the user to set the loader to either `Loader` (current interface) or `LoaderContext` (new interface) and depending on where the loader is used, i.e., `Get()` or `GetContext()`, the error returned from the loader would be either discarded or passed through to the caller.

So the end result would be as follows:
- The `Options` type: the user is now able to use `Loader` or `LoaderContext` when setting the loader (`WithLoader()` func).
- The `Get(key K, opts Options) Item` method: if the normal `Loader` is used -> no changes; if the new `LoaderContext` is used -> pass `context.Background()` as a context argument and discard the returned error (if any).
- `GetContext(context.Context, key K, opts Options) (Item, error)` method: if the normal `Loader` is used -> same result as with `Get()` and the error is `nil`; if the new `LoaderContext` is used -> use the provided context parameter and return the loader's error to the caller.

I think this way the API will remain simple, but at the same time it won't hinder people whose loader implementations are more complex.

Let me know what you think.

**Comment by wit221** [comment]
For added context, here is how I utilize the cache with the current API, with one type per cache. The db fetch happens in `Load` and utilizes the context saved on the `Loader`.

entitycache.go:
```
package entitycache

import (
	"context"
	"time"

	"go.uber.org/fx"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"

	"github.com/jellydator/ttlcache/v3"
	"github.com/samsarahq/go/oops"
)

const (
	Capacity     = 10000
	ItemDuration = 48 * time.Hour
)

type K struct {
	Kind  models.EntityKind
	Title string
}

type V struct {
	Entity *models.Entity
}

type EntityCache struct {
	*ttlcache.Cache[K, V]

	AppModels *models.Models
}

type Params struct {
	fx.In
	AppModels *models.Models
}

func New(p Params) (*EntityCache, error) {
	entityCache := &EntityCache{
		AppModels: p.AppModels,
	}

	cache := ttlcache.New(
		ttlcache.WithCapacity[K, V](Capacity),
		ttlcache.WithTTL[K, V](1*time.Hour),
		ttlcache.WithDisableTouchOnHit[K, V](),
	)

	entityCache.Cache = cache

	return entityCache, nil
}

type Loader struct {
	*models.Models
	Ctx  context.Context
	Args *models.ByKindTitleArgs

	Err error
}

func (l *Loader) Load(c *ttlcache.Cache[K, V], key K) *ttlcache.Item[K, V] {
	entity, err := l.Entity.ByKindTitle(l.Ctx, l.Args) // Db fetch happens here.
	if err != nil {
		l.Err = err
		return nil
	}

	item := c.Set(key, V{entity}, ItemDuration)
	return item
}

func keyFromArgs(ctx context.Context, args *models.ByKindTitleArgs) (K, error) {
	return K{
		Kind:  args.Kind,
		Title: args.Title,
	}, nil
}

func (cec *EntityCache) ByKindTitle(ctx context.Context, args *models.ByKindTitleArgs) (*models.Entity, error) {
	span, ctx := tracer.StartSpanFromContext(ctx, "gqlserver.entitycache")
	span.SetOperationName("EntityCache::By")
	defer span.Finish()

	key, err := keyFromArgs(ctx, args)
	if err != nil {
		return nil, oops.Wrapf(err, "could not get args key")
	}

	loader := &Loader{
		Models: cec.AppModels,
		Ctx:    ctx,
		Args:   args,
	}

	item := cec.Cache.Get(key, ttlcache.WithLoader[K, V](loader))
	if loader.Err != nil {
		return nil, loader.Err
	}

	return item.Value().Entity, nil
}

func (cec *EntityCache) Start(ctx context.Context) {
	go cec.Cache.Start()
	go cec.LogStats(ctx)
}

func (cec *EntityCache) LogStats(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		case <-time.After(10 * time.Second):
			length := cec.Len()
			cMetric := cec.Metrics()

			cacheTypeTag := "cache_type:entity"
			ddog.Gauge("gql.cache.len", float64(length), cacheTypeTag)
			ddog.Gauge("gql.cache.evictions", float64(cMetric.Evictions), cacheTypeTag)
			ddog.Gauge("gql.cache.hits", float64(cMetric.Hits), cacheTypeTag)
			ddog.Gauge("gql.cache.misses", float64(cMetric.Misses), cacheTypeTag)
			ddog.Gauge("gql.cache.insertions", float64(cMetric.Insertions), cacheTypeTag)
			// fmt.Printf("EntityCache stats: len[%d] metrics[%+v]\n", cec.Len(), cec.Metrics())
		}
	}
}
```

Using the cache:
```
		entity, err := s.EntityCache.ByKindTitle(ctx, &models.ByKindTitleArgs{
			Kind:  kind,
			Title: *value,
		})
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				return false, nil
			}

			return false, oops.Wrapf(err, "could not fetch entity")
		}
```

It makes for an awkward structure, but it is manageable.

**Comment by rowanseymour** [comment]
@swithek the downside of that approach obviously is the mismatches of `Loader`/`LoaderContext` and `Get`/`GetContext` leading to discarding errors in the `LoaderContext`+`Get` which is not ideal.. but maybe that's not as bad as the duplication that would come from having a separate type. Not sure... I think for now it's simpler for me to just create a type that wraps `ttlcache.Cache`.

@wit221 interesting, thanks for sharing
