### ISSUE TITLE
Memory leak problem caused by deleting items from golang map

### ISSUE THREAD

**Issue by nijich** [jellydator/ttlcache#84]
Hello,
Since the data of ttlcache is actually stored in golang built-in map, I wonder that ttlcache has the same problem, as golang will not shrink the size of map when deleting items (https://github.com/golang/go/issues/20135). Is it true. If it is, can I use some way to solve the memory leak problem when using ttlcache? Thank you.

**Comment by swithek** [comment]
Hi. That's an interesting problem. Since it comes from the map implementation itself, I'm not sure how this can be solved in this package. If you have any ideas, feel free to share. However, after doing some (superficial) testing, I didn't see any major leaks, which might mean that this issue isn't deterministic.

Have you noticed any leaks in your system? Or are you concerned because of the issue you linked?

**Comment by nijich** [comment]
Sorry for that when I opened this issue, I misunderstand the content of that link. After reading some articles and testing with code, I think the problem is the map itself cannot shrink when an item of it being deleted. The map just mark the area. And when the new item being inserted, map will reuse the marked area, place the new item in the marked area instead of allocating new memory. So I guess only either 
- using too many maps in the same time, or 
- the map allocating a lot of memory at a time due to large number of items or large size of one item, but then it deletes most of it and never inserting so many items as before.
will cause the problem. 
Setting map to nil and creating a new one, transfering the items from old map to new map seems to be the only way to solve the problem at essence. However, for me, using the pointer for value rather than using the struct is enough to avoid problem I think.

**Comment by dx314** [comment]
Using a SwissMap would be a suitable way to solve this issue: https://github.com/dolthub/swiss
